/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { ERC20 } from "./ERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC20 } from "./IERC20";
export type { BDLockingContract } from "./BDLockingContract";
export type { SampleERC20 } from "./SampleERC20";

export { Ownable__factory } from "./factories/Ownable__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20Metadata__factory } from "./factories/IERC20Metadata__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { BDLockingContract__factory } from "./factories/BDLockingContract__factory";
export { SampleERC20__factory } from "./factories/SampleERC20__factory";
